name: GCP Workload Identity Test
on:
  push:
    branches:
      - main

jobs:
  test-auth:
    runs-on: ubuntu-latest
    env:
      # Change these for each repo
      GCP_PROJECT_ID: 'woven-sensor-470012-a6'
      GCP_PROJECT_NUMBER: '245127449165'
      SERVICE_ACCOUNT: 'workloadidentity-github@woven-sensor-470012-a6.iam.gserviceaccount.com'
    
    # CRITICAL: These permissions are required for OIDC to work
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # Format: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          workload_identity_provider: 'projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Verify Auth
        run: |
          gcloud storage buckets list

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
