name: GCP Workload Identity Test
on:
  push:
    branches:
      - main

jobs:
  test-auth:
    runs-on: ubuntu-latest
    
    # CRITICAL: These permissions are required for OIDC to work
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # Format: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          workload_identity_provider: 'projects/245127449165/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'workloadidentity-github@woven-sensor-470012-a6.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Verify Auth
        run: |
          gcloud auth list
          gcloud projects get-iam-policy woven-sensor-470012-a6 --flatten="bindings[].members" --format="table(bindings.role)"